### ISSUE TITLE
Open in another app

### ISSUE THREAD

**Issue by PepikVaio** [PepikVaio/remarkable_Extractor#4]
Give the choice to open the result in another application and than the reMarkable application.

**Comment by espenhk** [comment]
Love this! As an example, I might want to put it in my Files app, or stick it as an e-mail attachment sent via the Mail app.

**Comment by PepikVaio** [comment]
Okay, I'll look into it.

**Comment by PepikVaio** [comment]
Testing:

https://youtu.be/mGxUA8iF0c4

Do you like it?

**Comment by PepikVaio** [comment]
Done in update 1.1 (still beta)

**Comment by espenhk** [comment]
Didn't see this until now, sorry - yeah, looks amazing! Will definitely tset this, thanks 😁
